# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: hello_world
  jobs:
  - job: echo
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

- stage: sonar_cloud
  jobs:
  - job: echo1
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'project3'
        organization: 'FOX10147'
        scannerMode: 'Other'
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: true
        sqGradlePluginVersionChoice: 'specify'
        sonarQubeGradlePluginVersion: '2.6.1'
        checkStyleRunAnalysis: false
        findBugsRunAnalysis: false
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

  - job: echo2
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'