# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: hello_world
  jobs:
  - job: echo
    steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

- stage: 'Sonar_Cloud'
  jobs:
  - job: 'All_Sonar'
    steps:
    - task: SonarCloudPrepare@1
      inputs:
        SonarCloud: 'project3'
        organization: 'fox10147'
        scannerMode: 'Other'
    - task: Gradle@2
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        sonarQubeRunAnalysis: true
        sqGradlePluginVersionChoice: 'specify'
        sonarQubeGradlePluginVersion: '2.6.1'
        checkStyleRunAnalysis: false
        findBugsRunAnalysis: false
    - task: SonarCloudAnalyze@1
    - task: SonarCloudPublish@1
      inputs:
        pollingTimeoutSec: '300'

- stage: 'Docker'
  jobs:
  - job: 'Docker_Build'
    steps:
    - script: |
        sh 'chmod +x gradlew' 
        sh './gradlew build'
    - task: Docker@2
      displayName: 'Building image...'
      inputs:
        containerRegistry: 'docker-login'
        repository: 'fox10147/azure-spring'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
    - task: Docker@2
      displayName: 'pushing image to docker repository...'
      inputs:
        containerRegistry: 'docker-login'
        repository: 'fox10147/azure-spring'
        command: push
        tags: latest

- stage: echo2
  jobs:
  - job: echo3
    steps:
    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'